// Security tests for office connector TLS scoping (M3.1).
// Verifies the office connector no longer applies a process-wide TLS bypass
// (`NODE_TLS_REJECT_UNAUTHORIZED='0'`) and instead uses a per-request
// `https.Agent({ rejectUnauthorized: false })` scoped to loopback hosts only.

import * as fs from 'node:fs/promises';
import https from 'node:https';
import os from 'node:os';
import path from 'node:path';
import { afterAll, afterEach, beforeAll, describe, expect, it } from 'vitest';

type ServerModule = {
  __test: {
    loopbackHttpsRequest: (
      url: string,
      init?: {
        method?: string;
        headers?: Record<string, string>;
        body?: string;
        lookup?: (
          host: string,
          opts: unknown,
          cb: (err: NodeJS.ErrnoException | null, address: string, family: number) => void,
        ) => void;
      },
    ) => Promise<{
      ok: boolean;
      status: number;
      json: () => Promise<unknown>;
      text: () => Promise<string>;
    }>;
    loopbackHttpsAgent: https.Agent;
  };
};

let serverModule: ServerModule;
let stateDir = '';

const cleanupServers: Array<{ close: () => Promise<void> }> = [];

async function generateSelfSignedCert(): Promise<{ cert: Buffer; key: Buffer }> {
  // Reuse the synthetic cert generated by tests/setup.ts.
  const TLS_DIR = path.join(os.tmpdir(), 'mcp-office-test-tls');
  const cert = await fs.readFile(path.join(TLS_DIR, 'localhost-cert.pem'));
  const key = await fs.readFile(path.join(TLS_DIR, 'localhost-key.pem'));
  return { cert, key };
}

async function startSelfSignedHealthServer(): Promise<{ port: number; close: () => Promise<void> }> {
  const { cert, key } = await generateSelfSignedCert();
  const sockets = new Set<import('node:net').Socket>();
  const server = https.createServer({ cert, key }, (req, res) => {
    if (req.url === '/health') {
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ status: 'ok' }));
      return;
    }
    res.writeHead(404);
    res.end();
  });
  server.on('connection', (socket) => {
    sockets.add(socket);
    socket.once('close', () => sockets.delete(socket));
  });

  await new Promise<void>((resolve, reject) => {
    server.once('error', reject);
    server.listen(0, '127.0.0.1', () => resolve());
  });

  const address = server.address();
  if (!address || typeof address === 'string') {
    throw new Error('Failed to determine self-signed health server port.');
  }

  const wrapped = {
    port: address.port,
    close: async () => {
      for (const socket of sockets) {
        socket.destroy();
      }
      await new Promise<void>((resolve) => {
        server.close(() => resolve());
      });
    },
  };
  cleanupServers.push(wrapped);
  return wrapped;
}

beforeAll(async () => {
  // Per VAL-OFFICE-012: ensure the env var is unset before importing the module,
  // and that importing the module does NOT set it back to '0'.
  delete process.env.NODE_TLS_REJECT_UNAUTHORIZED;

  // The module reads REBEL_OFFICE_SIDECAR_STATE at import time to derive paths.
  stateDir = await fs.mkdtemp(path.join(os.tmpdir(), 'office-security-tls-'));
  process.env.REBEL_OFFICE_SIDECAR_STATE = path.join(stateDir, 'sidecar-state.json');

  serverModule = (await import('../src/index.js')) as unknown as ServerModule;
});

afterEach(async () => {
  for (const server of cleanupServers.splice(0)) {
    await server.close();
  }
});

afterAll(async () => {
  await fs.rm(stateDir, { recursive: true, force: true });
});

describe('office TLS scoping (M3.1)', () => {
  it('VAL-OFFICE-003 — exposes a per-request https.Agent with rejectUnauthorized: false', () => {
    expect(serverModule.__test.loopbackHttpsAgent).toBeInstanceOf(https.Agent);
    expect((serverModule.__test.loopbackHttpsAgent as unknown as { options: { rejectUnauthorized?: boolean } }).options.rejectUnauthorized).toBe(false);
  });

  it('VAL-OFFICE-010 — loopback HTTPS request via helper succeeds against a self-signed cert', async () => {
    const server = await startSelfSignedHealthServer();
    const response = await serverModule.__test.loopbackHttpsRequest(
      `https://127.0.0.1:${server.port}/health`,
    );
    expect(response.status).toBe(200);
    expect(response.ok).toBe(true);
    const body = (await response.json()) as { status: string };
    expect(body.status).toBe('ok');
  });

  it('VAL-OFFICE-010 — also succeeds for the "localhost" loopback name', async () => {
    const server = await startSelfSignedHealthServer();
    const response = await serverModule.__test.loopbackHttpsRequest(
      `https://localhost:${server.port}/health`,
      {
        // Force "localhost" to resolve to 127.0.0.1 (where the server actually
        // listens) — keeps the test free from /etc/hosts assumptions on CI.
        // Node 20+ uses `autoSelectFamily` by default, which calls lookup with
        // `options.all = true`; support both the legacy positional callback and
        // the new array form.
        lookup: ((_host: string, opts: { all?: boolean }, cb: Function) => {
          if (opts && opts.all) {
            cb(null, [{ address: '127.0.0.1', family: 4 }]);
          } else {
            cb(null, '127.0.0.1', 4);
          }
        }) as never,
      },
    );
    expect(response.status).toBe(200);
    expect(response.ok).toBe(true);
  });

  it('VAL-OFFICE-011 — non-loopback HTTPS request rejects an untrusted self-signed cert', async () => {
    const server = await startSelfSignedHealthServer();
    // Use a non-loopback hostname (`example.test`) and force DNS to point it at
    // the local self-signed server. The connector helper should detect that the
    // hostname is non-loopback and use the default https.Agent (i.e. NOT the
    // loopback agent), so the TLS handshake must fail with a cert-validation
    // error.
    let caught: NodeJS.ErrnoException | null = null;
    try {
      await serverModule.__test.loopbackHttpsRequest(
        `https://example.test:${server.port}/health`,
        {
          lookup: ((_host: string, opts: { all?: boolean }, cb: Function) => {
            if (opts && opts.all) {
              cb(null, [{ address: '127.0.0.1', family: 4 }]);
            } else {
              cb(null, '127.0.0.1', 4);
            }
          }) as never,
        },
      );
    } catch (err) {
      caught = err as NodeJS.ErrnoException;
    }
    expect(caught).toBeTruthy();
    const validTlsErrorCodes = [
      'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
      'SELF_SIGNED_CERT_IN_CHAIN',
      'DEPTH_ZERO_SELF_SIGNED_CERT',
      'ERR_TLS_CERT_ALTNAME_INVALID',
    ];
    expect(validTlsErrorCodes).toContain(caught?.code);
  });

  it('VAL-OFFICE-012 — process.env.NODE_TLS_REJECT_UNAUTHORIZED is NOT set to "0" after import', () => {
    const value = process.env.NODE_TLS_REJECT_UNAUTHORIZED;
    expect(value === undefined || value !== '0').toBe(true);
  });
});
