/**
 * Regression test for the output-directory TOCTOU (write side of the MED-1
 * pattern): the workspace fence approves the generated-image directory by
 * canonical path, but a local attacker able to modify the workspace could swap
 * the directory for a symlink between validation and the write, landing the
 * generated bytes outside the workspace/declared roots. The write path never
 * re-trusts the validated pathname: bytes are staged in a fresh mkdtemp
 * directory (0700) created atomically inside the canonical directory (which
 * contains no symlink components, so no swap can redirect it), written
 * through a single descriptor, and hard-linked into place. The directory's
 * canonical identity is re-verified before any bytes flow; a mid-flight swap
 * fails closed with WORKSPACE_FENCE_VIOLATION.
 */

import * as fs from 'node:fs';
import * as fsp from 'node:fs/promises';
import * as path from 'node:path';
import type { CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import { afterEach, describe, expect, it, vi } from 'vitest';
import {
  createInMemoryClientPair,
  extractToolPayload,
  importConnectorModule,
  makeImageBase64,
} from './helpers.js';

const cleanupTargets: string[] = [];

const makeTempDir = async (label: string): Promise<string> => {
  const dir = await fsp.mkdtemp(path.join('/tmp', `Acme-${label}-`));
  cleanupTargets.push(dir);
  return dir;
};

const mockOpenAIImageResponses = (): ReturnType<typeof vi.spyOn> =>
  vi.spyOn(globalThis, 'fetch').mockImplementation(async () => {
    return new Response(
      JSON.stringify({ data: [{ b64_json: makeImageBase64('png') }] }),
      {
        status: 200,
        headers: { 'Content-Type': 'application/json' },
      },
    );
  });

afterEach(async () => {
  vi.restoreAllMocks();
  vi.unstubAllEnvs();
  while (cleanupTargets.length > 0) {
    const target = cleanupTargets.pop();
    if (target) {
      await fsp.rm(target, { recursive: true, force: true });
    }
  }
});

describe('generated-image output write race', () => {
  it('refuses and cleans up when the output directory is swapped for a symlink after validation', async () => {
    const workspace = await makeTempDir('write-race-ws');
    const outside = await makeTempDir('write-race-outside');
    const outsideGenerated = path.join(outside, 'generated-images');
    await fsp.mkdir(outsideGenerated, { recursive: true });

    const connector = await importConnectorModule({
      MCP_WORKSPACE_PATH: workspace,
      OPENAI_API_KEY: 'sk-test-Acme-write-race',
    });
    mockOpenAIImageResponses();

    // Simulate the local race: by the time the connector opens the output
    // file, the validated Chief-of-Staff directory has been replaced by a
    // symlink pointing outside the workspace.
    const chiefOfStaffDir = path.join(workspace, 'Chief-of-Staff');
    const realOpen = fs.promises.open.bind(fs.promises);
    let swapped = false;
    vi.spyOn(fs.promises, 'open').mockImplementation((async (
      target: fs.PathLike,
      flags?: fs.OpenMode,
      mode?: fs.Mode,
    ) => {
      if (!swapped) {
        swapped = true;
        await fsp.rename(chiefOfStaffDir, `${chiefOfStaffDir}-original`);
        await fsp.symlink(outside, chiefOfStaffDir);
      }
      return realOpen(target, flags, mode);
    }) as typeof fs.promises.open);

    const pair = await createInMemoryClientPair(connector.createServer());
    try {
      const result = (await pair.client.callTool({
        name: 'generate_image',
        arguments: { prompt: 'Acme race probe', quality: 'medium' },
      })) as CallToolResult;

      expect(result.isError).toBe(true);
      const payload = extractToolPayload(result);
      expect(payload.code).toBe('WORKSPACE_FENCE_VIOLATION');
      expect(payload.error).toContain('changed while the image was being saved');

      // No generated file is left behind outside the fence.
      expect(await fsp.readdir(outsideGenerated)).toHaveLength(0);
    } finally {
      await pair.close();
    }
  });

  it('refuses before any bytes flow when the swap lands the staging directory itself outside the fence', async () => {
    const workspace = await makeTempDir('staging-race-ws');
    const outside = await makeTempDir('staging-race-outside');
    const outsideGenerated = path.join(outside, 'generated-images');
    await fsp.mkdir(outsideGenerated, { recursive: true });

    const connector = await importConnectorModule({
      MCP_WORKSPACE_PATH: workspace,
      OPENAI_API_KEY: 'sk-test-Acme-staging-race',
    });
    mockOpenAIImageResponses();

    // A faster race: the swap happens before the staging directory is
    // created, so staging itself is materialised through the symlink outside
    // the fence. The canonical-identity re-check must still refuse before any
    // image bytes are written, and cleanup must remove the misplaced staging
    // directory.
    const chiefOfStaffDir = path.join(workspace, 'Chief-of-Staff');
    const realMkdtemp = fs.promises.mkdtemp.bind(fs.promises);
    let swapped = false;
    vi.spyOn(fs.promises, 'mkdtemp').mockImplementation((async (
      prefix: string,
      options?: fs.ObjectEncodingOptions | null,
    ) => {
      if (!swapped && prefix.includes('.openai-image-staging-')) {
        swapped = true;
        await fsp.rename(chiefOfStaffDir, `${chiefOfStaffDir}-original`);
        await fsp.symlink(outside, chiefOfStaffDir);
      }
      return realMkdtemp(prefix, options);
    }) as typeof fs.promises.mkdtemp);

    const pair = await createInMemoryClientPair(connector.createServer());
    try {
      const result = (await pair.client.callTool({
        name: 'generate_image',
        arguments: { prompt: 'Acme staging race probe', quality: 'medium' },
      })) as CallToolResult;

      expect(result.isError).toBe(true);
      const payload = extractToolPayload(result);
      expect(payload.code).toBe('WORKSPACE_FENCE_VIOLATION');
      expect(payload.error).toContain('changed while the image was being saved');

      // The staging directory that briefly existed outside the fence is gone,
      // and no generated bytes were written there.
      expect(await fsp.readdir(outsideGenerated)).toHaveLength(0);
    } finally {
      await pair.close();
    }
  });

  it('still writes normally when the output directory is stable', async () => {
    const workspace = await makeTempDir('write-stable-ws');
    const connector = await importConnectorModule({
      MCP_WORKSPACE_PATH: workspace,
      OPENAI_API_KEY: 'sk-test-Acme-write-stable',
    });
    mockOpenAIImageResponses();
    const pair = await createInMemoryClientPair(connector.createServer());

    try {
      const result = (await pair.client.callTool({
        name: 'generate_image',
        arguments: { prompt: 'Acme stable write', quality: 'medium' },
      })) as CallToolResult;

      expect(result.isError).not.toBe(true);
      const outputDir = path.join(workspace, 'Chief-of-Staff', 'generated-images');
      const saved = await fsp.readdir(outputDir);
      expect(saved).toHaveLength(1);
      const written = await fsp.readFile(path.join(outputDir, saved[0] as string));
      // Bytes on disk carry the PNG signature.
      expect([...written.subarray(0, 4)]).toEqual([0x89, 0x50, 0x4e, 0x47]);
    } finally {
      await pair.close();
    }
  });
});
