import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { klingFetch } from '../client.js';
import { withErrorHandling } from '../utils.js';
import { taskCreatedResponseSchema } from '../types.js';
import { unwrapUntrusted, wrapUntrusted } from '../untrusted-content.js';

/** Envelope source label for vendor-controlled strings in tool output. */
const KLING_SOURCE = 'kling-api';

export function registerExtendTools(server: McpServer): void {
  // ─── extend_kling_video ─────────────────────────────────────────
  server.registerTool(
    'extend_kling_video',
    {
      description:
        'Continue (extend) a video previously generated by Kling, adding roughly 4-5 seconds per extension.\n\n' +
        'WORKFLOW:\n' +
        '1. You need the video_id of a Kling-generated video (from check_kling_task or list_kling_tasks, valid for 30 days after generation)\n' +
        '2. Call this tool → returns a new task_id\n' +
        '3. Wait 30 seconds, then call check_kling_task(task_id, task_type="video-extend")\n' +
        '4. Repeat until status is "succeed". Each extension adds ~4-5s; chain calls for longer videos.',
      inputSchema: z.object({
        video_id: z
          .string()
          .min(1)
          .describe(
            'ID of a video generated by Kling (the video.id from a completed task result, NOT the task_id). Must have been generated within the last 30 days.',
          ),
        prompt: z
          .string()
          .optional()
          .describe('How the video should continue: next action, camera movement. Max 2500 chars.'),
        negative_prompt: z
          .string()
          .optional()
          .describe('Things to avoid in the extension: "blurry, distorted faces, watermark"'),
        callback_url: z
          .string()
          .url()
          .optional()
          .describe(
            'HTTPS URL that Kling POSTs the task result to when the task status changes. Optional — polling with check_kling_task works without it.',
          ),
      }),
      annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
    },
    withErrorHandling(async (args) => {
      if (args.callback_url && !args.callback_url.startsWith('https://')) {
        return JSON.stringify({
          ok: false,
          error: 'callback_url must use HTTPS',
          code: 'INVALID_URL',
        });
      }

      const body: Record<string, unknown> = { video_id: unwrapUntrusted(args.video_id) };
      if (args.prompt) body.prompt = args.prompt;
      if (args.negative_prompt) body.negative_prompt = args.negative_prompt;
      if (args.callback_url) body.callback_url = args.callback_url;

      const result = await klingFetch('/videos/video-extend', taskCreatedResponseSchema, {
        method: 'POST',
        body: JSON.stringify(body),
      });

      const taskId = wrapUntrusted(result.task_id, KLING_SOURCE)!;
      return JSON.stringify({
        ok: true,
        task_id: taskId,
        task_type: 'video-extend',
        status: 'submitted',
        message: `Video extension started. Use check_kling_task with task_id "${taskId}" and task_type "video-extend" to poll for completion.`,
        nextPollSeconds: 30,
      });
    }),
  );
}
