import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { klingFetch } from '../client.js';
import { encodeLocalAudio } from '../media.js';
import { withErrorHandling } from '../utils.js';
import { taskCreatedResponseSchema } from '../types.js';
import { unwrapUntrusted, wrapUntrusted } from '../untrusted-content.js';

/** Envelope source label for vendor-controlled strings in tool output. */
const KLING_SOURCE = 'kling-api';

export function registerLipSyncTools(server: McpServer): void {
  // ─── generate_kling_lip_sync ────────────────────────────────────
  server.registerTool(
    'generate_kling_lip_sync',
    {
      description:
        'Make a person in a video speak: generates a lip-synced version of a Kling video from text (text-to-speech) or an audio file.\n\n' +
        'WORKFLOW:\n' +
        '1. Identify the video: video_id (from a completed Kling task) or video_url (public HTTPS .mp4/.mov, ≤100MB, 2-10s, 720p/1080p)\n' +
        '2. Choose mode:\n' +
        '   - "text2video": Kling speaks your text — requires text (max 120 chars) + voice_id\n' +
        '   - "audio2video": sync to your own audio — requires audio_url (HTTPS) or audio_path (local file)\n' +
        '3. Call this tool → returns task_id, then poll with check_kling_task(task_id, task_type="lip-sync")\n\n' +
        'AUDIO (audio2video): .mp3/.wav/.m4a/.aac, max 5MB. audio_path must be inside MCP_WORKSPACE_PATH (or the system temp directory).',
      inputSchema: z.object({
        video_id: z
          .string()
          .optional()
          .describe(
            'ID of a video generated by Kling (the video.id from a completed task result, NOT the task_id). 5-10s videos generated within the last 30 days. Provide either video_id or video_url, not both.',
          ),
        video_url: z
          .string()
          .url()
          .optional()
          .describe(
            'Public HTTPS URL of the video to lip-sync (.mp4/.mov, ≤100MB, 2-10s, 720p or 1080p). Provide either video_id or video_url, not both.',
          ),
        mode: z
          .enum(['text2video', 'audio2video'])
          .describe('"text2video": Kling speaks the text. "audio2video": sync to a supplied audio file.'),
        text: z
          .string()
          .max(120)
          .optional()
          .describe('The spoken text (max 120 characters). Required when mode is "text2video".'),
        voice_id: z
          .string()
          .optional()
          .describe(
            'Voice ID from the Kling voice catalog (see https://app.klingai.com/global/dev/document-api). Required when mode is "text2video".',
          ),
        voice_language: z
          .enum(['zh', 'en'])
          .optional()
          .describe('Voice language. Default: zh (Kling default).'),
        voice_speed: z
          .number()
          .min(0.8)
          .max(2.0)
          .optional()
          .describe('Speech rate, 0.8-2.0. Default: 1.0.'),
        audio_url: z
          .string()
          .url()
          .optional()
          .describe(
            'Public HTTPS URL of the audio file (.mp3/.wav/.m4a/.aac, max 5MB). Required when mode is "audio2video" unless audio_path is given.',
          ),
        audio_path: z
          .string()
          .optional()
          .describe(
            'Absolute path to a local audio file inside MCP_WORKSPACE_PATH (or the system temp directory). Formats: .mp3/.wav/.m4a/.aac, max 5MB.',
          ),
        callback_url: z
          .string()
          .url()
          .optional()
          .describe(
            'HTTPS URL that Kling POSTs the task result to when the task status changes. Optional — polling with check_kling_task works without it.',
          ),
      }),
      annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: true },
    },
    withErrorHandling(async (args) => {
      // Exactly one of video_id / video_url.
      if (args.video_id && args.video_url) {
        return JSON.stringify({
          ok: false,
          error: 'Provide either video_id or video_url, not both.',
          code: 'INVALID_INPUT',
        });
      }
      if (!args.video_id && !args.video_url) {
        return JSON.stringify({
          ok: false,
          error: 'Provide a video: either video_id (from a completed Kling task) or video_url (public HTTPS URL).',
          code: 'INVALID_INPUT',
        });
      }
      if (args.video_url && !args.video_url.startsWith('https://')) {
        return JSON.stringify({ ok: false, error: 'video_url must use HTTPS', code: 'INVALID_URL' });
      }
      if (args.callback_url && !args.callback_url.startsWith('https://')) {
        return JSON.stringify({ ok: false, error: 'callback_url must use HTTPS', code: 'INVALID_URL' });
      }

      const input: Record<string, unknown> = { mode: args.mode };
      if (args.video_id) input.video_id = unwrapUntrusted(args.video_id);
      if (args.video_url) input.video_url = args.video_url;

      if (args.mode === 'text2video') {
        if (!args.text) {
          return JSON.stringify({
            ok: false,
            error: 'text is required when mode is "text2video".',
            code: 'INVALID_INPUT',
          });
        }
        if (!args.voice_id) {
          return JSON.stringify({
            ok: false,
            error: 'voice_id is required when mode is "text2video".',
            code: 'INVALID_INPUT',
          });
        }
        input.text = args.text;
        input.voice_id = args.voice_id;
        if (args.voice_language) input.voice_language = args.voice_language;
        if (args.voice_speed !== undefined) input.voice_speed = args.voice_speed;
      } else {
        // audio2video — exactly one of audio_url / audio_path.
        if (args.audio_url && args.audio_path) {
          return JSON.stringify({
            ok: false,
            error: 'Provide either audio_url or audio_path, not both.',
            code: 'INVALID_INPUT',
          });
        }
        if (!args.audio_url && !args.audio_path) {
          return JSON.stringify({
            ok: false,
            error: 'audio_url or audio_path is required when mode is "audio2video".',
            code: 'INVALID_INPUT',
          });
        }
        if (args.audio_url) {
          if (!args.audio_url.startsWith('https://')) {
            return JSON.stringify({ ok: false, error: 'audio_url must use HTTPS', code: 'INVALID_URL' });
          }
          input.audio_type = 'url';
          input.audio_url = args.audio_url;
        } else {
          // Local file: workspace-fenced read, Base64-encoded into the request.
          input.audio_type = 'file';
          input.audio_file = encodeLocalAudio(args.audio_path!);
        }
      }

      const body: Record<string, unknown> = { input };
      if (args.callback_url) body.callback_url = args.callback_url;

      const result = await klingFetch('/videos/lip-sync', taskCreatedResponseSchema, {
        method: 'POST',
        body: JSON.stringify(body),
      });

      const taskId = wrapUntrusted(result.task_id, KLING_SOURCE)!;
      return JSON.stringify({
        ok: true,
        task_id: taskId,
        task_type: 'lip-sync',
        status: 'submitted',
        message: `Lip-sync task started. Use check_kling_task with task_id "${taskId}" and task_type "lip-sync" to poll for completion.`,
        nextPollSeconds: 30,
      });
    }),
  );
}
